openapi: 3.0.0
info:
  title: category
  version: 1.0.0
paths:
  /api/v1/categories:
    post:
      summary: create-category
      operationId: create-category
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
      requestBody:
        $ref: '#/components/requestBodies/create-category'
    get:
      summary: read-categories
      operationId: read-categories
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
  /api/v1/categories/a417822c-e7e9-4b06-812a-a641c4137d37:
    delete:
      summary: delete-category-id
      operationId: delete-category-id
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
    get:
      summary: read-category-id
      operationId: read-category-id
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
    put:
      summary: update-category-id
      operationId: update-category-id
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/update-category-id'
  /api/v1/categories/by-slug/plats-principaux:
    get:
      summary: read-category-by-slug
      operationId: read-category-by-slug
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
servers:
  - url: http://localhost:3000
components:
  schemas:
    create-category:
      type: object
      properties:
        name:
          type: string
        iconName:
          type: string
        color:
          type: string
        sortOrder:
          type: number
    update-category-id:
      type: object
      properties:
        name:
          type: string
        iconName:
          type: string
        color:
          type: string
        sortOrder:
          type: number
  requestBodies:
    create-category:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create-category'
      description: ''
      required: true
    update-category-id:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/update-category-id'
      description: ''
      required: true
  securitySchemes: {}
