openapi: 3.0.0
info:
  title: favorite
  version: 1.0.0
paths:
  /api/v1/recipes/efabc8cf-6e97-4519-b2fb-efc7624978d0/favorite:
    post:
      summary: add-recipe-to-favorite
      operationId: add-recipe-to-favorite
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
      security:
        add-recipe-to-favorite: []
    delete:
      summary: remove-recipe-from-favorite
      operationId: remove-recipe-from-favorite
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
      security:
        remove-recipe-from-favorite: []
  /api/v1/me/favorites:
    get:
      summary: read-user-recipe-favorite
      operationId: read-user-recipe-favorite
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: page
          in: query
          description: ''
          required: true
          example: '1'
        - name: limit
          in: query
          description: ''
          required: true
          example: '10'
        - name: sortBy
          in: query
          description: ''
          required: true
          example: createdAt
        - name: sortOrder
          in: query
          description: ''
          required: true
          example: desc
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
      security:
        read-user-recipe-favorite: []
servers:
  - url: http://localhost:3000
components:
  schemas: {}
  requestBodies: {}
  securitySchemes:
    add-recipe-to-favorite:
      type: http
      scheme: bearer
    read-user-recipe-favorite-sort-cooktime:
      type: http
      scheme: bearer
    read-user-recipe-favorite-sort-preptime:
      type: http
      scheme: bearer
    read-user-recipe-favorite-sort-viewcount:
      type: http
      scheme: bearer
    read-user-recipe-favorite-sort:
      type: http
      scheme: bearer
    read-user-recipe-favorite:
      type: http
      scheme: bearer
    remove-recipe-from-favorite:
      type: http
      scheme: bearer
