openapi: 3.0.0
info:
  title: public_api_key
  version: 1.0.0
paths:
  /api/v1/api-key/generate:
    post:
      summary: generate api key
      operationId: generate api key
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
      security:
        generate_api_key: []
  /api/v1/recipes/35d1e1f1-34d8-4c9c-afde-59fed7d93381:
    get:
      summary: recipe
      operationId: recipe
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: >-
            cs_661a324c-47fb-4b61-aaa5-aae783dc94c3_1767848230_df0465c5.5goFIdr2_1YSREeT2aUaPxPQKPGGJshe
      security:
        recipe: []
  /api/v1/recipes:
    get:
      summary: recipes
      operationId: recipes
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: >-
            cs_661a324c-47fb-4b61-aaa5-aae783dc94c3_1767848230_df0465c5.5goFIdr2_1YSREeT2aUaPxPQKPGGJshe
      security:
        recipes: []
  /api/v1/users:
    get:
      summary: users
      operationId: users
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: >-
            cs_661a324c-47fb-4b61-aaa5-aae783dc94c3_1767848230_df0465c5.5goFIdr2_1YSREeT2aUaPxPQKPGGJshe
      security:
        users: []
servers:
  - url: http://localhost:3000
components:
  schemas: {}
  requestBodies: {}
  securitySchemes:
    generate_api_key:
      type: http
      scheme: bearer
    recipe:
      type: http
      scheme: bearer
    recipes:
      type: http
      scheme: bearer
    users:
      type: http
      scheme: bearer
