openapi: 3.0.0
info:
  title: recipe
  version: 1.0.0
paths:
  /api/v1/recipes:
    post:
      summary: create-recipe
      operationId: create-recipe
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
      requestBody:
        $ref: '#/components/requestBodies/create-recipe'
      security:
        create-recipe: []
    get:
      summary: read-recipes
      operationId: read-recipes
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
  /api/v1/recipes/efabc8cf-6e97-4519-b2fb-efc7624978d0:
    delete:
      summary: delete-recipe
      operationId: delete-recipe
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
      security:
        delete-recipe: []
    get:
      summary: read-recipes-id
      operationId: read-recipes-id
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
    put:
      summary: update-recipe
      operationId: update-recipe
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
      requestBody:
        $ref: '#/components/requestBodies/update-recipe'
      security:
        update-recipe: []
  /api/v1/recipes/by-slug/poulet-tikka-masala:
    get:
      summary: read-recipes-by-slug
      operationId: read-recipes-by-slug
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-gateway-api-key
          in: header
          description: ''
          required: true
          example: AGK.h40KjfWN3Vc3mS0CcX9rV7Jx2uWfhjfxHv59eOeEAdM
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
servers:
  - url: http://localhost:3000
components:
  schemas:
    create-recipe:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        prepTime:
          type: number
        cookTime:
          type: number
        servings:
          type: number
        difficulty:
          type: string
        isPublished:
          type: boolean
        authorId:
          type: string
        categoryId:
          type: string
        ingredients:
          type: array
          items:
            type: string
          properties:
            '0':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '1':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '2':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '3':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '4':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '5':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '6':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '7':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '8':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '9':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
        instructions:
          type: array
          items:
            type: string
          properties:
            '0':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '1':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '2':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '3':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '4':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '5':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '6':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '7':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
    update-recipe:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        prepTime:
          type: number
        cookTime:
          type: number
        servings:
          type: number
        difficulty:
          type: string
        isPublished:
          type: boolean
        categoryId:
          type: string
        ingredients:
          type: array
          items:
            type: string
          properties:
            '0':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '1':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '2':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '3':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '4':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '5':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '6':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '7':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '8':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
            '9':
              type: object
              properties:
                name:
                  type: string
                quantityText:
                  type: string
                isOptional:
                  type: boolean
        instructions:
          type: array
          items:
            type: string
          properties:
            '0':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '1':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '2':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '3':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '4':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '5':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '6':
              type: object
              properties:
                stepNumber:
                  type: number
                description:
                  type: string
            '7':
              type: object
              properties:
                id:
                  type: string
                stepNumber:
                  type: number
                description:
                  type: string
  requestBodies:
    create-recipe:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create-recipe'
      description: ''
      required: true
    update-recipe:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/update-recipe'
      description: ''
      required: true
  securitySchemes:
    create-recipe:
      type: http
      scheme: bearer
    delete-recipe:
      type: http
      scheme: bearer
    update-recipe:
      type: http
      scheme: bearer
